export const work = [
  {
    slug: 'ai-powered-disputes-workspace',
    title: 'An AI-Powered Disputes Workspace',
    category: 'Interaction Design',
    company: 'ServiceNow',
    timeline: '2025 — Present',
    role: 'Principal Designer',
    accent: 'from-[#FF3D81] to-[#0A0A0A]',
    description: 'Leading design for the Visa DPS (Disputes Processing System) Workspace — Now Assist-powered onboarding, Customer 360, and Interaction Record.',
    overview: 'The Disputes Processing System workspace needed a foundation for AI-assisted interactions spanning onboarding, a unified customer view, and interaction history — serving FSO and cross-industry verticals like Healthcare, Telecom, and Manufacturing.',
    outcome: null,
    videoUrl: null,
    responsibilities: null,
  },
  {
    slug: 'mercado-design-language',
    title: 'Mercado: LinkedIn’s Next-Generation Design Language',
    category: 'Design Systems',
    company: 'LinkedIn',
    timeline: '2018 — 2025',
    role: 'Principal Designer',
    accent: 'from-[#D9FF3D] to-[#0A0A0A]',
    description: 'Designing LinkedIn’s next-generation design language, codenamed Mercado.',
    overview: 'As LinkedIn’s product surface grew across web, mobile, and enterprise tools, teams needed a shared design language that could scale consistently — Mercado became that foundation.',
    outcome: null,
    videoUrl: null,
    responsibilities: null,
  },
  {
    slug: 'sales-navigator-ai-features',
    title: 'AI-Powered Features for Sales Navigator',
    category: 'Product Design',
    company: 'LinkedIn',
    timeline: '2018 — 2025',
    role: 'Principal Designer',
    accent: 'from-[#3DDBFF] to-[#0A0A0A]',
    description: 'Leading the Sales Solutions team in transforming the Sales Navigator experience with AI-powered features to help sellers close deals more effectively.',
    overview: 'Sales Navigator needed AI-assisted capabilities that helped sellers work more effectively without adding noise or overstepping their judgment on which relationships and deals to prioritize.',
    outcome: null,
    videoUrl: null,
    responsibilities: null,
  },
  {
    slug: 'linkedin-profile-entity-pages',
    title: 'Profile & Entity Pages at LinkedIn',
    category: 'UX / Information Design',
    company: 'LinkedIn',
    timeline: '2014 — 2016',
    role: 'Senior User Experience Designer',
    accent: 'from-[#FF3D81]/70 to-[#0A0A0A]',
    description: 'Optimizing the profile experience on LinkedIn’s Identity team, and building a framework for entity pages spanning Company, Jobs, Groups, Education, and Skills.',
    overview: 'The profile experience needed better editing tools, media support, and personal branding controls, while entity pages across the platform needed a consistent framework instead of one-off treatments.',
    outcome: null,
    videoUrl: null,
    responsibilities: null,
  },
  {
    slug: 'art-deco-design-system',
    title: 'The Art Deco Design System',
    category: 'Design Systems',
    company: 'LinkedIn',
    timeline: '2016 — 2018',
    role: 'Staff UX Designer',
    accent: 'from-[#D9FF3D]/70 to-[#0A0A0A]',
    description: 'Leading LinkedIn’s Art Deco Design System — reusable components and design foundations adopted company-wide.',
    overview: 'LinkedIn’s products needed shared, accessible, and performant design foundations instead of each team building components independently.',
    outcome: 'Reusable components and design foundations adopted company-wide, with standards set for accessibility and performance.',
    videoUrl: null,
    responsibilities: null,
  },
  {
    slug: 'mpbt-marketing-playbook',
    title: 'A Marketing & Communications Playbook',
    category: 'Design Operations',
    company: 'Monterey Peninsula Ballet Theatre',
    timeline: '2025 — Present',
    role: 'Board Member — Marketing & Communications',
    accent: 'from-[#3DDBFF]/70 to-[#0A0A0A]',
    description: 'Developing a Marketing & Communications playbook for the Monterey Peninsula Ballet Theatre’s board.',
    overview: 'As a board member leading marketing and communications, the organization needed consistent practices across website, social, email, and text outreach instead of ad hoc efforts each time.',
    outcome: 'A documented playbook with best practices and templates, built to scale future marketing and communications efforts.',
    videoUrl: null,
    responsibilities: null,
  },
];

export function getWorkBySlug(slug) {
  return work.find((item) => item.slug === slug);
}

export function getNextWork(slug) {
  const index = work.findIndex((item) => item.slug === slug);
  if (index === -1) return work[0];
  return work[(index + 1) % work.length];
}
